### ISSUE TITLE
Something wrong with requirements file

### ISSUE THREAD

**Issue by tomersagi** [WorldHistoricalGazetteer/whgazetteer#73]
Trying to install the requirements file results in multiple errors.

```
Collecting typer[all]>=0.3
  Downloading typer-0.6.0-py3-none-any.whl (38 kB)
  Downloading typer-0.5.0-py3-none-any.whl (28 kB)
  Downloading typer-0.4.2-py3-none-any.whl (27 kB)
  Downloading typer-0.4.1-py3-none-any.whl (27 kB)
Collecting urllib3[secure,socks]~=1.26
  Downloading urllib3-1.26.11-py2.py3-none-any.whl (139 kB)
     |████████████████████████████████| 139 kB 70.2 MB/s 
  Downloading urllib3-1.26.10-py2.py3-none-any.whl (139 kB)
     |████████████████████████████████| 139 kB 30.7 MB/s 
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 73.3 MB/s 
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 74.1 MB/s 
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 65.3 MB/s 
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 65.5 MB/s 
  Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 68.1 MB/s 
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 66.4 MB/s 
  Downloading urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
     |████████████████████████████████| 137 kB 66.6 MB/s 
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 44.3 MB/s 
  Downloading urllib3-1.26.1-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 74.0 MB/s 
  Downloading urllib3-1.26.0-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 67.9 MB/s 
INFO: pip is looking at multiple versions of typer[all] to determine which version is compatible with other requirements. This could take a while.
Collecting typer[all]>=0.3
  Downloading typer-0.3.2-py3-none-any.whl (21 kB)
  Downloading typer-0.3.1-py3-none-any.whl (21 kB)
  Downloading typer-0.3.0-py3-none-any.whl (21 kB)
INFO: pip is looking at multiple versions of pyjwt[crypto] to determine which version is compatible with other requirements. This could take a while.
Collecting pyjwt[crypto]>=1.7
  Downloading PyJWT-2.2.0-py3-none-any.whl (16 kB)
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
  Downloading PyJWT-2.0.1-py3-none-any.whl (15 kB)
  Downloading PyJWT-2.0.0-py3-none-any.whl (15 kB)
  Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
  Downloading PyJWT-1.7.0-py2.py3-none-any.whl (18 kB)
INFO: pip is looking at multiple versions of pip to determine which version is compatible with other requirements. This could take a while.
Collecting pip>=10.0.1
  Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 45.8 MB/s 
  Downloading pip-22.2.1-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 49.8 MB/s 
  Downloading pip-22.2-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 51.8 MB/s 
  Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 36.3 MB/s 
  Downloading pip-22.1.1-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 45.9 MB/s 
  Downloading pip-22.1-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 49.3 MB/s 
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 42.9 MB/s 
  Downloading pip-22.0.3-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 45.0 MB/s 
  Downloading pip-22.0.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 38.6 MB/s 
  Downloading pip-22.0.1-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 68.2 MB/s 
  Downloading pip-22.0-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 46.3 MB/s 
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 51.5 MB/s 
  Downloading pip-21.3-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 49.2 MB/s 
  Downloading pip-21.2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 67.7 MB/s 
  Downloading pip-21.2.3-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 49.7 MB/s 
  Downloading pip-21.2.2-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 47.3 MB/s 
  Downloading pip-21.2.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 50.3 MB/s 
  Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 50.2 MB/s 
  Downloading pip-21.1.2-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 46.2 MB/s 
  Downloading pip-21.1.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 48.3 MB/s 
  Downloading pip-21.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 49.0 MB/s 
  Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 50.5 MB/s 
  Downloading pip-21.0-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 46.6 MB/s 
  Downloading pip-20.3.4-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 42.3 MB/s 
  Downloading pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 39.2 MB/s 
  Downloading pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 56.0 MB/s 
  Downloading pip-20.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 46.4 MB/s 
  Downloading pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 47.3 MB/s 
  Downloading pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 50.2 MB/s 
  Downloading pip-20.2.2-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 44.0 MB/s 
  Downloading pip-20.2.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 44.4 MB/s 
  Downloading pip-20.2-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 47.6 MB/s 
  Downloading pip-20.1.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 48.9 MB/s 
  Downloading pip-20.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 48.6 MB/s 
  Downloading pip-20.0.2-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 48.8 MB/s 
  Downloading pip-20.0.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 40.6 MB/s 
  Downloading pip-19.3.1-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 52.8 MB/s 
  Downloading pip-19.3-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 38.2 MB/s 
  Downloading pip-19.2.3-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 51.1 MB/s 
  Downloading pip-19.2.2-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 46.1 MB/s 
  Downloading pip-19.2.1-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 46.6 MB/s 
  Downloading pip-19.2-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 49.8 MB/s 
  Downloading pip-19.1.1-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 38.5 MB/s 
  Downloading pip-19.1-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 54.6 MB/s 
  Downloading pip-19.0.3-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 54.6 MB/s 
  Downloading pip-19.0.2-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 42.6 MB/s 
  Downloading pip-19.0.1-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 49.4 MB/s 
  Downloading pip-19.0-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 36.7 MB/s 
  Downloading pip-18.1-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 47.7 MB/s 
  Downloading pip-18.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 33.4 MB/s 
  Downloading pip-10.0.1-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 50.7 MB/s 
INFO: pip is looking at multiple versions of typer[all] to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyjwt[crypto] to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pip to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of greenlet to determine which version is compatible with other requirements. This could take a while.
Collecting greenlet!=0.4.17
  Using cached greenlet-1.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (154 kB)
  Downloading greenlet-1.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (153 kB)
     |████████████████████████████████| 153 kB 67.2 MB/s 
  Downloading greenlet-1.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
     |████████████████████████████████| 147 kB 70.8 MB/s 
  Downloading greenlet-1.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (162 kB)
     |████████████████████████████████| 162 kB 72.4 MB/s 
  Downloading greenlet-1.0.0-cp39-cp39-manylinux2010_x86_64.whl (163 kB)
     |████████████████████████████████| 163 kB 70.1 MB/s 
  Downloading greenlet-0.4.16.tar.gz (60 kB)
     |████████████████████████████████| 60 kB 8.8 MB/s 
  Downloading greenlet-0.4.15.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 6.5 MB/s 
  Downloading greenlet-0.4.14.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 7.4 MB/s 
  Downloading greenlet-0.4.13.tar.gz (58 kB)
     |████████████████████████████████| 58 kB 6.7 MB/s 
  Downloading greenlet-0.4.12.tar.gz (57 kB)
     |████████████████████████████████| 57 kB 5.4 MB/s 
  Downloading greenlet-0.4.11.zip (82 kB)
     |████████████████████████████████| 82 kB 1.3 MB/s 
  Downloading greenlet-0.4.10.zip (82 kB)
     |████████████████████████████████| 82 kB 931 kB/s 
  Downloading greenlet-0.4.9.zip (78 kB)
     |████████████████████████████████| 78 kB 6.4 MB/s 
  Downloading greenlet-0.4.7.zip (77 kB)
     |████████████████████████████████| 77 kB 6.7 MB/s 
  Downloading greenlet-0.4.6.zip (77 kB)
     |████████████████████████████████| 77 kB 7.8 MB/s 
  Downloading greenlet-0.4.5.zip (77 kB)
     |████████████████████████████████| 77 kB 6.2 MB/s 
  Downloading greenlet-0.4.4.zip (76 kB)
     |████████████████████████████████| 76 kB 286 kB/s 
  Downloading greenlet-0.4.3.zip (76 kB)
     |████████████████████████████████| 76 kB 5.2 MB/s 
  Downloading greenlet-0.4.2.zip (74 kB)
     |████████████████████████████████| 74 kB 3.2 MB/s 
  Downloading greenlet-0.4.1.zip (75 kB)
     |████████████████████████████████| 75 kB 5.2 MB/s 
  Downloading greenlet-0.4.0.zip (72 kB)
     |████████████████████████████████| 72 kB 1.6 MB/s 
  Downloading greenlet-0.3.4.zip (63 kB)
     |████████████████████████████████| 63 kB 1.9 MB/s 
  Downloading greenlet-0.3.3.zip (65 kB)
     |████████████████████████████████| 65 kB 4.5 MB/s 
  Downloading greenlet-0.3.2.zip (50 kB)
     |████████████████████████████████| 50 kB 6.3 MB/s 
  Downloading greenlet-0.3.1.tar.gz (39 kB)
  Downloading greenlet-0.3.tar.gz (37 kB)
  Downloading greenlet-0.2.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-imxmjlu3/greenlet_5d340dca96ec470c9505bc65c426fc41/setup.py'"'"'; __file__='"'"'/tmp/pip-install-imxmjlu3/greenlet_5d340dca96ec470c9505bc65c426fc41/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m39cxfpy
         cwd: /tmp/pip-install-imxmjlu3/greenlet_5d340dca96ec470c9505bc65c426fc41/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-imxmjlu3/greenlet_5d340dca96ec470c9505bc65c426fc41/setup.py", line 3, in <module>
        import ez_setup
      File "/tmp/pip-install-imxmjlu3/greenlet_5d340dca96ec470c9505bc65c426fc41/ez_setup/__init__.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/72/db/0d1a944ba1517256e8b1a080a90297569d8662442631a6b05f8a1c584556/greenlet-0.2.tar.gz#sha256=d1919d283f7e7a2cbb474c620efb703811408026f8c6b25f923acd8b49deebaa (from https://pypi.org/simple/greenlet/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading greenlet-0.1.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-imxmjlu3/greenlet_d10b172dca90463092cbf48b9276ab1e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-imxmjlu3/greenlet_d10b172dca90463092cbf48b9276ab1e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l602nyyo
         cwd: /tmp/pip-install-imxmjlu3/greenlet_d10b172dca90463092cbf48b9276ab1e/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-imxmjlu3/greenlet_d10b172dca90463092cbf48b9276ab1e/setup.py", line 3, in <module>
        import ez_setup
      File "/tmp/pip-install-imxmjlu3/greenlet_d10b172dca90463092cbf48b9276ab1e/ez_setup/__init__.py", line 176
        print "Setuptools version",version,"or greater has been installed."
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/6d/59d9a80285c4fef1254d4f589dda87d593e7316082ff94ad2f277eafca22/greenlet-0.1.tar.gz#sha256=5d71dd7e5acb64333c387fbf215f0019ffcdaeab46bb4d30f9ff6ccc94e41710 (from https://pypi.org/simple/greenlet/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tomersagi** [comment]
ok, letting it run to the end reveals the following conflicts:

```
ERROR: Cannot install -r requirements397.txt (line 201), -r requirements397.txt (line 73), PyJWT==2.3.0, pyjwt[crypto]==1.7.0, pyjwt[crypto]==1.7.1, pyjwt[crypto]==2.0.0, pyjwt[crypto]==2.0.1, pyjwt[crypto]==2.1.0, pyjwt[crypto]==2.2.0 and pyjwt[crypto]==2.4.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested PyJWT==2.3.0
    djangorestframework-simplejwt 4.8.0 depends on pyjwt<3 and >=2
    social-auth-core 4.2.0 depends on PyJWT>=2.0.0
    pyjwt[crypto] 2.4.0 depends on pyjwt 2.4.0 (from https://files.pythonhosted.org/packages/1c/fb/b82e9601b00d88cf8bbee1f39b855ae773f9d5bcbcedb3801b2f72460696/PyJWT-2.4.0-py3-none-any.whl#sha256=72d1d253f32dbd4f5c88eaf1fdc62f3a19f676ccbadb9dbc5d07e951b2b26daf (from https://pypi.org/simple/pyjwt/) (requires-python:>=3.6))
    The user requested PyJWT==2.3.0
    djangorestframework-simplejwt 4.8.0 depends on pyjwt<3 and >=2
    social-auth-core 4.2.0 depends on PyJWT>=2.0.0
    pyjwt[crypto] 2.2.0 depends on pyjwt 2.2.0 (from https://files.pythonhosted.org/packages/7d/5a/8ec21f8c4159708919b6cb5c203a1537349fd05265d2d88609493b462875/PyJWT-2.2.0-py3-none-any.whl#sha256=b0ed5824c8ecc5362e540c65dc6247567db130c4226670bf7699aec92fb4dae1 (from https://pypi.org/simple/pyjwt/) (requires-python:>=3.6))
    The user requested PyJWT==2.3.0
    djangorestframework-simplejwt 4.8.0 depends on pyjwt<3 and >=2
    social-auth-core 4.2.0 depends on PyJWT>=2.0.0
    pyjwt[crypto] 2.1.0 depends on pyjwt 2.1.0 (from https://files.pythonhosted.org/packages/3f/32/d5d3cab27fee7f6b22d7cd7507547ae45d52e26030fa77d1f83d0526c6e5/PyJWT-2.1.0-py3-none-any.whl#sha256=934d73fbba91b0483d3857d1aff50e96b2a892384ee2c17417ed3203f173fca1 (from https://pypi.org/simple/pyjwt/) (requires-python:>=3.6))
    The user requested PyJWT==2.3.0
    djangorestframework-simplejwt 4.8.0 depends on pyjwt<3 and >=2
    social-auth-core 4.2.0 depends on PyJWT>=2.0.0
    pyjwt[crypto] 2.0.1 depends on pyjwt 2.0.1 (from https://files.pythonhosted.org/packages/b4/9b/8850f99027ed029af6828199cc87179eaccbbf1f9e6e373e7f0177d32dad/PyJWT-2.0.1-py3-none-any.whl#sha256=b70b15f89dc69b993d8a8d32c299032d5355c82f9b5b7e851d1a6d706dffe847 (from https://pypi.org/simple/pyjwt/) (requires-python:>=3.6))
    The user requested PyJWT==2.3.0
    djangorestframework-simplejwt 4.8.0 depends on pyjwt<3 and >=2
    social-auth-core 4.2.0 depends on PyJWT>=2.0.0
    pyjwt[crypto] 2.0.0 depends on pyjwt 2.0.0 (from https://files.pythonhosted.org/packages/91/5f/5cff1c3696e0d574f5741396550c9a308dde40704d17e39e94b89c07d789/PyJWT-2.0.0-py3-none-any.whl#sha256=5c2ff2eb27d7e342dfc3cafcc16412781f06db2690fbef81922b0172598f085b (from https://pypi.org/simple/pyjwt/) (requires-python:>=3.6))
    The user requested PyJWT==2.3.0
    djangorestframework-simplejwt 4.8.0 depends on pyjwt<3 and >=2
    social-auth-core 4.2.0 depends on PyJWT>=2.0.0
    pyjwt[crypto] 1.7.1 depends on pyjwt 1.7.1 (from https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl#sha256=5c6eca3c2940464d106b99ba83b00c6add741c9becaec087fb7ccdefea71350e (from https://pypi.org/simple/pyjwt/))
    The user requested PyJWT==2.3.0
    djangorestframework-simplejwt 4.8.0 depends on pyjwt<3 and >=2
    social-auth-core 4.2.0 depends on PyJWT>=2.0.0
    pyjwt[crypto] 1.7.0 depends on pyjwt 1.7.0 (from https://files.pythonhosted.org/packages/02/9b/16c92330f1fb76e3f6372ba6f804d412ec894ee1d9ea31516269b5f6add4/PyJWT-1.7.0-py2.py3-none-any.whl#sha256=00414bfef802aaecd8cc0d5258b6cb87bd8f553c2986c2c5f29b19dd5633aeb7 (from https://pypi.org/simple/pyjwt/))

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by kgeographer** [comment]
Just finished creating and testing [a routine for standing up a local instance of WHG](https://github.com/WorldHistoricalGazetteer/whgazetteer/blob/main/docs/cloning/cloning.md), and there is now [a `reqmin.txt` file](https://github.com/WorldHistoricalGazetteer/whgazetteer/blob/main/reqmin.txt) in the project root, which so far _appears to_ enable all functionality.
